// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYrYm1aR_f_TF-nkQpzeP0LWZyzsJubkE',
    appId: '1:468970710343:web:87d724abafbb508c739862',
    messagingSenderId: '468970710343',
    projectId: 'dash-buy',
    authDomain: 'dash-buy.firebaseapp.com',
    storageBucket: 'dash-buy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRE0LnpGx2Zmu0n_PPWdLBfEJQxfTBELw',
    appId: '1:468970710343:android:da447aeafa09e717739862',
    messagingSenderId: '468970710343',
    projectId: 'dash-buy',
    storageBucket: 'dash-buy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5838dsfCpMA14Mtp2RLJWnX8ItyrZ1o',
    appId: '1:468970710343:ios:d04f5fa097d00e6d739862',
    messagingSenderId: '468970710343',
    projectId: 'dash-buy',
    storageBucket: 'dash-buy.appspot.com',
    iosBundleId: 'com.example.flutterDashBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK5838dsfCpMA14Mtp2RLJWnX8ItyrZ1o',
    appId: '1:468970710343:ios:c8f7d18d10fea8f7739862',
    messagingSenderId: '468970710343',
    projectId: 'dash-buy',
    storageBucket: 'dash-buy.appspot.com',
    iosBundleId: 'com.example.flutterDashBuy.RunnerTests',
  );
}
